-- =====================================================
-- SlideFlow Database Checkpoint
-- Created: 2026-02-12T18:44:52-07:00
-- Project: uxfnxnucdiawcyhexfat
-- =====================================================
-- To restore: run this entire file against your Supabase
-- database via the SQL Editor or psql.
-- =====================================================

BEGIN;

-- =====================================================
-- 1. TABLE DEFINITIONS
-- =====================================================

-- Drop existing tables (in dependency order)
DROP TABLE IF EXISTS public.content_cat CASCADE;
DROP TABLE IF EXISTS public.show CASCADE;
DROP TABLE IF EXISTS public.content CASCADE;
DROP TABLE IF EXISTS public.device CASCADE;
DROP TABLE IF EXISTS public.folders CASCADE;
DROP TABLE IF EXISTS public.credentials CASCADE;
DROP TABLE IF EXISTS public.category CASCADE;
DROP TABLE IF EXISTS public.client CASCADE;
DROP TABLE IF EXISTS public.location CASCADE;
DROP TABLE IF EXISTS public.permission CASCADE;
DROP TABLE IF EXISTS public.dev_type CASCADE;

-- dev_type
CREATE TABLE public.dev_type (
  dev_type text NOT NULL PRIMARY KEY,
  dev_name text NOT NULL
);

-- permission
CREATE TABLE public.permission (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL
);

-- category
CREATE TABLE public.category (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  parent_id integer REFERENCES public.category(id),
  created_at timestamptz DEFAULT now()
);

-- client
CREATE TABLE public.client (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL
);

-- location
CREATE TABLE public.location (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  loc_name text NOT NULL,
  wifi_name text,
  uname text,
  pword text,
  otp text
);

-- credentials
CREATE TABLE public.credentials (
  id uuid NOT NULL PRIMARY KEY,
  username text UNIQUE,
  first_name text,
  last_name text,
  permission_id integer REFERENCES public.permission(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- device
CREATE TABLE public.device (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  mac text NOT NULL,
  device_type text NOT NULL REFERENCES public.dev_type(dev_type) ON DELETE RESTRICT
);

-- folders
CREATE TABLE public.folders (
  id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid REFERENCES public.folders(id) ON DELETE CASCADE,
  name text NOT NULL,
  security_level text DEFAULT 'inherit',
  allowed_roles text[],
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- content
CREATE TABLE public.content (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  length text,
  description text,
  file_url text,
  thumbnail_url text,
  mime_type text,
  file_size bigint,
  folder_id uuid REFERENCES public.folders(id),
  type text,
  duration integer,
  metadata jsonb DEFAULT '{}',
  created_by uuid,
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- content_cat
CREATE TABLE public.content_cat (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content_id integer NOT NULL REFERENCES public.content(id) ON DELETE CASCADE,
  cat_id integer NOT NULL REFERENCES public.category(id) ON DELETE CASCADE,
  UNIQUE(content_id, cat_id)
);

-- show
CREATE TABLE public.show (
  id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  content_id integer REFERENCES public.content(id) ON DELETE CASCADE,
  device_id integer REFERENCES public.device(id) ON DELETE CASCADE,
  location_id integer REFERENCES public.location(id) ON DELETE CASCADE,
  client_id integer REFERENCES public.client(id) ON DELETE CASCADE,
  start_time timestamptz,
  finish_time timestamptz,
  name text DEFAULT 'Untitled',
  slides_data jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- =====================================================
-- 2. DATA
-- =====================================================

-- credentials (2 rows)
INSERT INTO public.credentials (id, username, first_name, last_name, permission_id, created_at, updated_at) VALUES
  ('4971e568-e26c-48a5-aedd-a28e72e48313', NULL, 'Slide', 'Flow', NULL, '2026-02-12 05:43:01.1885+00', '2026-02-12 05:43:01.1885+00'),
  ('4c969ba2-3807-41a2-a3a6-5ac5644b0dcd', 'shawn92017@gmail.com', '', '', NULL, '2026-02-13 01:04:34.673115+00', '2026-02-13 01:16:41.414+00');

-- category (5 rows)
INSERT INTO public.category (id, name, parent_id, created_at) VALUES
  (1, 'Image', NULL, '2026-02-12 08:24:08.091314+00'),
  (2, 'Video', NULL, '2026-02-12 08:24:08.091314+00'),
  (3, 'Audio', NULL, '2026-02-12 08:24:08.091314+00'),
  (4, 'Document', NULL, '2026-02-12 08:24:08.091314+00'),
  (5, 'Other', NULL, '2026-02-12 08:24:08.091314+00');

-- Reset category sequence
SELECT setval(pg_get_serial_sequence('public.category', 'id'), (SELECT COALESCE(MAX(id), 0) FROM public.category));

-- folders (2 rows)
INSERT INTO public.folders (id, parent_id, name, security_level, allowed_roles, created_at, updated_at) VALUES
  ('479955ef-a5e7-44db-907b-1d7e8c3907f2', NULL, 'test', 'inherit', NULL, '2026-02-12 07:13:02.900528+00', '2026-02-12 07:13:02.900528+00'),
  ('5e0024fa-67a2-4ff6-9d3a-fcafcf05411e', NULL, 'images', 'inherit', NULL, '2026-02-12 21:34:09.505192+00', '2026-02-12 21:34:09.505192+00');

-- content (3 rows)
INSERT INTO public.content (id, name, length, description, file_url, thumbnail_url, mime_type, file_size, folder_id, type, duration, metadata, created_by, status, created_at, updated_at) VALUES
  (1, 'test.jpg', NULL, NULL, 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/default-team/1770880655173-test.jpg', 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/default-team/1770880655173-test.jpg', 'image/jpeg', 6563, '479955ef-a5e7-44db-907b-1d7e8c3907f2', 'image', NULL, '{}', NULL, 'active', '2026-02-12 07:17:34.600442+00', '2026-02-12 07:17:34.600442+00'),
  (2, 'test.jpg', NULL, NULL, 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/uploads/1770881031162-test.jpg', 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/uploads/1770881031162-test.jpg', 'image/jpeg', 6563, '479955ef-a5e7-44db-907b-1d7e8c3907f2', 'image', NULL, '{}', NULL, 'active', '2026-02-12 07:23:50.896705+00', '2026-02-12 07:23:50.896705+00'),
  (4, 'download (1).jpg', NULL, NULL, 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/uploads/1770945011146-download%20(1).jpg', 'https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/uploads/1770945011146-download%20(1).jpg', 'image/jpeg', 5648, '5e0024fa-67a2-4ff6-9d3a-fcafcf05411e', 'image', NULL, '{}', NULL, 'active', '2026-02-13 01:10:11.199438+00', '2026-02-13 01:10:11.199438+00');

-- Reset content sequence
SELECT setval(pg_get_serial_sequence('public.content', 'id'), (SELECT COALESCE(MAX(id), 0) FROM public.content));

-- content_cat (3 rows)
INSERT INTO public.content_cat (id, content_id, cat_id) VALUES
  (1, 1, 1),
  (2, 2, 1),
  (4, 4, 1);

-- Reset content_cat sequence
SELECT setval(pg_get_serial_sequence('public.content_cat', 'id'), (SELECT COALESCE(MAX(id), 0) FROM public.content_cat));

-- show (2 rows)
INSERT INTO public.show (id, content_id, device_id, location_id, client_id, start_time, finish_time, name, slides_data, created_at, updated_at) VALUES
  (3, 2, NULL, NULL, NULL, '2026-02-12 00:58:00+00', '2026-02-12 00:58:00+00', 'test.jpg', '[{"id":"2","name":"Slide 1","duration":10,"elements":[{"x":0,"y":0,"id":"y7i5bgsl1","src":"https://uxfnxnucdiawcyhexfat.supabase.co/storage/v1/object/public/content/uploads/1770881031162-test.jpg","type":"image","style":{},"width":960,"height":540}],"backgroundColor":"#ffffff"}]', '2026-02-12 07:58:32.981214+00', '2026-02-12 07:58:32.981214+00'),
  (6, NULL, NULL, NULL, NULL, NULL, NULL, 'test2', '[{"id":"zmb68cfu5","name":"Slide 1","duration":10,"elements":[{"x":394,"y":171,"id":"96uln30fr","src":"https://images.pexels.com/photos/33289065/pexels-photo-33289065.jpeg?auto=compress&cs=tinysrgb&h=350","type":"image","style":{},"width":300,"height":200}],"backgroundColor":"#ffffff"}]', '2026-02-12 08:12:15.417726+00', '2026-02-12 08:12:21.499+00');

-- Reset show sequence
SELECT setval(pg_get_serial_sequence('public.show', 'id'), (SELECT COALESCE(MAX(id), 0) FROM public.show));

-- =====================================================
-- 3. ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_cat ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dev_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permission ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.show ENABLE ROW LEVEL SECURITY;

-- category policies
CREATE POLICY "Allow anon read category" ON public.category FOR SELECT TO anon USING (true);
CREATE POLICY "Allow authenticated all category" ON public.category FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can insert categories" ON public.category FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read categories" ON public.category FOR SELECT TO authenticated USING (true);

-- client policies
CREATE POLICY "Authenticated users can insert clients" ON public.client FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read clients" ON public.client FOR SELECT TO authenticated USING (true);

-- content policies
CREATE POLICY "Anon users can delete content" ON public.content FOR DELETE TO anon USING (true);
CREATE POLICY "Anon users can insert content" ON public.content FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon users can read content" ON public.content FOR SELECT TO anon USING (true);
CREATE POLICY "Anon users can update content" ON public.content FOR UPDATE TO anon USING (true);
CREATE POLICY "Authenticated users can insert content" ON public.content FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read content" ON public.content FOR SELECT TO authenticated USING (true);

-- content_cat policies
CREATE POLICY "Allow anon insert content_cat" ON public.content_cat FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon read content_cat" ON public.content_cat FOR SELECT TO anon USING (true);
CREATE POLICY "Allow authenticated all content_cat" ON public.content_cat FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated users can insert content_cat" ON public.content_cat FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read content_cat" ON public.content_cat FOR SELECT TO authenticated USING (true);

-- credentials policies
CREATE POLICY "Allow anon read credentials" ON public.credentials FOR SELECT TO anon USING (true);
CREATE POLICY "Allow authenticated all credentials" ON public.credentials FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Anyone can view profiles" ON public.credentials FOR SELECT TO public USING (true);
CREATE POLICY "Users can update their own profile" ON public.credentials FOR UPDATE TO public USING (auth.uid() = id);

-- dev_type policies
CREATE POLICY "Authenticated users can insert dev_type" ON public.dev_type FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read dev_type" ON public.dev_type FOR SELECT TO authenticated USING (true);

-- device policies
CREATE POLICY "Authenticated users can insert devices" ON public.device FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read devices" ON public.device FOR SELECT TO authenticated USING (true);

-- folders policies
CREATE POLICY "Anon users can delete folders" ON public.folders FOR DELETE TO anon USING (true);
CREATE POLICY "Anon users can insert folders" ON public.folders FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon users can read folders" ON public.folders FOR SELECT TO anon USING (true);
CREATE POLICY "Anon users can update folders" ON public.folders FOR UPDATE TO anon USING (true);
CREATE POLICY "Authenticated users can delete folders" ON public.folders FOR DELETE TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert folders" ON public.folders FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read folders" ON public.folders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can update folders" ON public.folders FOR UPDATE TO authenticated USING (true);

-- location policies
CREATE POLICY "Authenticated users can insert locations" ON public.location FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read locations" ON public.location FOR SELECT TO authenticated USING (true);

-- permission policies
CREATE POLICY "Authenticated users can insert permissions" ON public.permission FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read permissions" ON public.permission FOR SELECT TO authenticated USING (true);

-- show policies
CREATE POLICY "Anon users can delete shows" ON public.show FOR DELETE TO anon USING (true);
CREATE POLICY "Anon users can insert shows" ON public.show FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon users can read shows" ON public.show FOR SELECT TO anon USING (true);
CREATE POLICY "Anon users can update shows" ON public.show FOR UPDATE TO anon USING (true);
CREATE POLICY "Auth users can delete shows" ON public.show FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth users can insert shows" ON public.show FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth users can read shows" ON public.show FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth users can update shows" ON public.show FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert shows" ON public.show FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read shows" ON public.show FOR SELECT TO authenticated USING (true);

-- =====================================================
-- 4. FUNCTIONS & TRIGGERS
-- =====================================================

-- handle_new_user function (auto-creates credentials row on signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.credentials (id, username, first_name, last_name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'first_name',
    NEW.raw_user_meta_data ->> 'last_name'
  );
  RETURN NEW;
END;
$function$;

-- Trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================
-- 5. STORAGE BUCKETS
-- =====================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('content', 'content', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

COMMIT;

-- =====================================================
-- CHECKPOINT COMPLETE
-- =====================================================
